version: "2"

checks:
  method-lines:
    enabled: true
    config:
      threshold: 50

engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50

  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
