---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50

  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
